services:
  - type: web
    name: hippo-tech
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_DIR
        value: /data
      - key: UPLOADS_DIR
        value: /data/uploads
    disk:
      name: hippo-data
      mountPath: /data
      sizeGB: 1
